### ISSUE TITLE
Doesn’t work on Atom 1.14

### ISSUE THREAD

**Issue by j-f1** [facebook-atom/nuclide-prebuilt-libs#11]
When I try to open the terminal on Atom 1.14.0, I get this error message instead of a functioning terminal:

```
For more info check out the docs: https://nuclide.io/docs/features/terminal
Error starting process:
Error: Cannot find module '/Users/jed/.atom/packages/atom-ide-ui/node_modules/nuclide-prebuilt-libs/pty/build/pty-node-v64-darwin-x64/pty.node'
```

Could you rebuild these libraries for the latest version?

**Comment by Lucky4Luuk** [comment]
v64 has been compiled. Check the releases. Should be in there.

**Comment by j-f1** [comment]
I had to manually modify the package.json of `atom-ide-ui` to allow installing the latest version of `nuclide-prebuilt-libs`, but once I did that and restarted the editor, everything worked.
